I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 211, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 211, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 319, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
OSError: Couldn't find file 'gui/window_icon.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/main.py", line 652, in main
    run(restart)
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/execution.py", line 958, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 211, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 211, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 319, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/display/core.py", line 2172, in interact
    self.start()
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/display/core.py", line 1018, in start
    self.post_init()
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/display/core.py", line 1107, in post_init
    self.set_icon()
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/display/core.py", line 1151, in set_icon
    with renpy.loader.load(icon, directory="images") as f:
  File "/Users/zjackson1233/Documents/renpy-8.3.4-sdk/renpy/loader.py", line 686, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'gui/window_icon.png'.

macOS-12.7.5-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Game 1.0
Wed Jan 15 08:47:15 2025
